# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user.mailer.rest:
        class: AppBundle\Mailer\RestMailer
        public: false
        parent: fos_user.mailer.twig_swift

    event.jwt_created_listener:
        class: AppBundle\Event\Listener\JWTCreatedListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
